spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
data-sources:
  - name: data-base-1
    strategy: h2
    url: jdbc:h2:~/test
    table: TEST
    user:
    password:
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
  - name: data-base-2
    strategy: h2
    url: jdbc:h2:~/test
    table: TEST
    user:
    password:
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name